### ISSUE TITLE
Bug and Feature templates

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/helpwave#41]
```[tasklist]
### Tasks
- [ ] Bug template for helpwave/services
- [ ] Feature template for helpwave/services
- [ ] Bug template for helpwave/web
- [ ] Bug template for helpwave/web
```
